### PR TITLE
meredith has added a poem

### PR DESCRIPTION
**Pull request by meredith-j**
new poem (same format), new author (by me), new image (sourced by me). also, changed background to magenta. please approve pull. thanks!

### CODE REVIEW

**Comment by kimcangho** [comment]
Hi Meredith, that's some snark you got there! Just check the colour and we should be good to go!

**Comment by kimcangho** [comment]
P.S: We can't merge unless the colour is changed!

**Comment by meredith-j** [comment]
Hey Kent! Nice catch. Seems like maroon has become the new background colour after a team vote. Merge conflicts have been fixed. Let me know if you need anything else - but we should be all good on my end.
Meredith

**Comment by kimcangho** [comment]
Looks good to me! Maroon is a go for background colour!

**Review by kimcangho — APPROVED** [review]
Like I said, we are a go! New bgcolour! New Poem! New Image!

**Pull request merged**
